package org.myEncuesta.persistence.hibernate;
// Generated Apr 3, 2017 10:52:47 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.myEncuesta.persistence.interfaces.IAllowedToResponsePoll;

/**
 * AllowedToResponsePoll generated by hbm2java
 */
@Entity
@Table(name = "AllowedToResponsePoll", schema = "dbo", catalog = "myEncuesta")
public class AllowedToResponsePoll implements java.io.Serializable, IAllowedToResponsePoll {

	private Integer id;
	private Polls polls;
	private String email;

	public AllowedToResponsePoll() {
	}

	public AllowedToResponsePoll(Polls polls) {
		this.polls = polls;
	}

	public AllowedToResponsePoll(Polls polls, String email) {
		this.polls = polls;
		this.email = email;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IAllowedToResponsePoll#getId()
	 */
	@Override
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IAllowedToResponsePoll#setId(java.lang.Integer)
	 */
	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IAllowedToResponsePoll#getPolls()
	 */
	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Polls_id", nullable = false)
	public Polls getPolls() {
		return this.polls;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IAllowedToResponsePoll#setPolls(org.myEncuesta.persistence.hibernate.Polls)
	 */
	@Override
	public void setPolls(Polls polls) {
		this.polls = polls;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IAllowedToResponsePoll#getEmail()
	 */
	@Override
	@Column(name = "eMail")
	public String getEmail() {
		return this.email;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IAllowedToResponsePoll#setEmail(java.lang.String)
	 */
	@Override
	public void setEmail(String email) {
		this.email = email;
	}

}
