package org.myEncuesta.persistence.hibernate;
// Generated Apr 3, 2017 10:52:47 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users", schema = "dbo", catalog = "myEncuesta")
public class Users implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String mail;
	private Date birdDate;
	private String gender;
	private Boolean isOperator;
	private String passwordHash;
	private Set<Responses> responseses = new HashSet<Responses>(0);

	public Users() {
	}

	public Users(String userName, String mail, Date birdDate, String gender, Boolean isOperator, String passwordHash,
			Set<Responses> responseses) {
		this.userName = userName;
		this.mail = mail;
		this.birdDate = birdDate;
		this.gender = gender;
		this.isOperator = isOperator;
		this.passwordHash = passwordHash;
		this.responseses = responseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "mail")
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birdDate", length = 10)
	public Date getBirdDate() {
		return this.birdDate;
	}

	public void setBirdDate(Date birdDate) {
		this.birdDate = birdDate;
	}

	@Column(name = "gender", length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "isOperator")
	public Boolean getIsOperator() {
		return this.isOperator;
	}

	public void setIsOperator(Boolean isOperator) {
		this.isOperator = isOperator;
	}

	@Column(name = "passwordHash")
	public String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Responses> getResponseses() {
		return this.responseses;
	}

	public void setResponseses(Set<Responses> responseses) {
		this.responseses = responseses;
	}

}
