package org.myEncuesta.persistence.hibernate;
// Generated Apr 3, 2017 10:52:47 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.myEncuesta.persistence.interfaces.IDataListItems;

/**
 * DataListsItems generated by hbm2java
 */
@Entity
@Table(name = "DataListsItems", schema = "dbo", catalog = "myEncuesta")
public class DataListsItems implements java.io.Serializable, IDataListItems {

	private Integer id;
	private Integer groupList;
	private String label;
	private Set<DataList> dataLists = new HashSet<DataList>(0);

	public DataListsItems() {
	}

	public DataListsItems(Integer groupList, String label, Set<DataList> dataLists) {
		this.groupList = groupList;
		this.label = label;
		this.dataLists = dataLists;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataListItems#getId()
	 */
	@Override
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataListItems#setId(java.lang.Integer)
	 */
	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataListItems#getGroupList()
	 */
	@Override
	@Column(name = "groupList")
	public Integer getGroupList() {
		return this.groupList;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataListItems#setGroupList(java.lang.Integer)
	 */
	@Override
	public void setGroupList(Integer groupList) {
		this.groupList = groupList;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataListItems#getLabel()
	 */
	@Override
	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataListItems#setLabel(java.lang.String)
	 */
	@Override
	public void setLabel(String label) {
		this.label = label;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataListItems#getDataLists()
	 */
	@Override
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataListsItems")
	public Set<DataList> getDataLists() {
		return this.dataLists;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataListItems#setDataLists(java.util.Set)
	 */
	@Override
	public void setDataLists(Set<DataList> dataLists) {
		this.dataLists = dataLists;
	}

}
