package org.myEncuesta.persistence.hibernate;
// Generated Apr 3, 2017 10:52:47 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.myEncuesta.persistence.interfaces.IDataList;
import org.myEncuesta.persistence.interfaces.IDataListItems;

/**
 * DataList generated by hbm2java
 */
@Entity
@Table(name = "DataList", schema = "dbo", catalog = "myEncuesta")
public class DataList implements java.io.Serializable, IDataList {

	private Integer id;
	private IDataListItems dataListsItems;
	private String name;
	private Set<QuestionFields> questionFieldses = new HashSet<QuestionFields>(0);

	public DataList() {
	}

	public DataList(IDataListItems dataListsItems) {
		this.dataListsItems = dataListsItems;
	}

	public DataList(IDataListItems dataListsItems, String name, Set<QuestionFields> questionFieldses) {
		this.dataListsItems = dataListsItems;
		this.name = name;
		this.questionFieldses = questionFieldses;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataList#getId()
	 */
	@Override
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataList#setId(java.lang.Integer)
	 */
	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataList#getDataListsItems()
	 */
	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DataListsItems_id", nullable = false)
	public IDataListItems getDataListsItems() {
		return this.dataListsItems;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataList#setDataListsItems(org.myEncuesta.persistence.hibernate.DataListsItems)
	 */
	@Override
	public void setDataListsItems(IDataListItems dataListsItems) {
		this.dataListsItems = dataListsItems;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataList#getName()
	 */
	@Override
	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataList#setName(java.lang.String)
	 */
	@Override
	public void setName(String name) {
		this.name = name;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataList#getQuestionFieldses()
	 */
	@Override
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataList")
	public Set<QuestionFields> getQuestionFieldses() {
		return this.questionFieldses;
	}

	/* (non-Javadoc)
	 * @see org.myEncuesta.persistence.hibernate.IDataList#setQuestionFieldses(java.util.Set)
	 */
	@Override
	public void setQuestionFieldses(Set<QuestionFields> questionFieldses) {
		this.questionFieldses = questionFieldses;
	}

}
