package org.myEncuesta.persistence.hibernate;
// Generated Apr 3, 2017 10:52:47 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pages generated by hbm2java
 */
@Entity
@Table(name = "Pages", schema = "dbo", catalog = "myEncuesta")
public class Pages implements java.io.Serializable {

	private Integer id;
	private Polls polls;
	private String title;
	private String expressionShow;
	private Integer showOrder;
	private Set<Questions> questionses = new HashSet<Questions>(0);
	private Set<Responses> responseses = new HashSet<Responses>(0);

	public Pages() {
	}

	public Pages(Polls polls) {
		this.polls = polls;
	}

	public Pages(Polls polls, String title, String expressionShow, Integer showOrder, Set<Questions> questionses,
			Set<Responses> responseses) {
		this.polls = polls;
		this.title = title;
		this.expressionShow = expressionShow;
		this.showOrder = showOrder;
		this.questionses = questionses;
		this.responseses = responseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Polls_id", nullable = false)
	public Polls getPolls() {
		return this.polls;
	}

	public void setPolls(Polls polls) {
		this.polls = polls;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "expressionShow")
	public String getExpressionShow() {
		return this.expressionShow;
	}

	public void setExpressionShow(String expressionShow) {
		this.expressionShow = expressionShow;
	}

	@Column(name = "showOrder")
	public Integer getShowOrder() {
		return this.showOrder;
	}

	public void setShowOrder(Integer showOrder) {
		this.showOrder = showOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pages")
	public Set<Questions> getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set<Questions> questionses) {
		this.questionses = questionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pages")
	public Set<Responses> getResponseses() {
		return this.responseses;
	}

	public void setResponseses(Set<Responses> responseses) {
		this.responseses = responseses;
	}

}
