package org.myEncuesta.persistence.hibernate;
// Generated Apr 3, 2017 10:52:47 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Responses generated by hbm2java
 */
@Entity
@Table(name = "Responses", schema = "dbo", catalog = "myEncuesta")
public class Responses implements java.io.Serializable {

	private Integer id;
	private Pages pages;
	private PollResponsesHeader pollResponsesHeader;
	private QuestionFields questionFields;
	private Questions questions;
	private Users users;
	private String responseValues;

	public Responses() {
	}

	public Responses(Pages pages, PollResponsesHeader pollResponsesHeader, QuestionFields questionFields,
			Questions questions, Users users) {
		this.pages = pages;
		this.pollResponsesHeader = pollResponsesHeader;
		this.questionFields = questionFields;
		this.questions = questions;
		this.users = users;
	}

	public Responses(Pages pages, PollResponsesHeader pollResponsesHeader, QuestionFields questionFields,
			Questions questions, Users users, String responseValues) {
		this.pages = pages;
		this.pollResponsesHeader = pollResponsesHeader;
		this.questionFields = questionFields;
		this.questions = questions;
		this.users = users;
		this.responseValues = responseValues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Pages_id", nullable = false)
	public Pages getPages() {
		return this.pages;
	}

	public void setPages(Pages pages) {
		this.pages = pages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PollResponsesHeader_id", nullable = false)
	public PollResponsesHeader getPollResponsesHeader() {
		return this.pollResponsesHeader;
	}

	public void setPollResponsesHeader(PollResponsesHeader pollResponsesHeader) {
		this.pollResponsesHeader = pollResponsesHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QuestionFields_id", nullable = false)
	public QuestionFields getQuestionFields() {
		return this.questionFields;
	}

	public void setQuestionFields(QuestionFields questionFields) {
		this.questionFields = questionFields;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Questions_id", nullable = false)
	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "responseValues")
	public String getResponseValues() {
		return this.responseValues;
	}

	public void setResponseValues(String responseValues) {
		this.responseValues = responseValues;
	}

}
